
# tap repositories and their packages

tap homebrew/core
brew autojump
brew brotli
brew c-ares
brew ca-certificates
brew fzf
brew gh
brew icu4c
brew jq
brew libnghttp2
brew libuv
brew lz4
brew mpdecimal
brew node
brew oniguruma
brew openssl@1.1
brew pcre
brew python@3.11
brew readline
brew sqlite
brew the_silver_searcher
brew tree
brew vercel-cli
brew xz
brew zig
brew zstd

tap homebrew/cask
cask 1password
cask arc
cask beeper
cask cron
cask docker
cask figma
cask linear-linear
cask obsidian
cask protonvpn
cask raycast
cask signal
cask spotify
cask telegram
cask transmission
cask tripmode
cask warp
cask zoom

tap homebrew/services

tap koekeishiya/formulae
brew skhd
brew yabai

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask visual-studio-code-insiders

# App Store applications
appstore 682658836 GarageBand (10.4.6)
appstore 408981434 iMovie (10.3.4)
appstore 409183694 Keynote (12.1)
appstore 409203825 Numbers (12.1)
appstore 409201541 Pages (12.1)
