# This is the configuration file for the Z shell (Zsh).

# Basic Zsh Config
# Set various options for the shell, such as command history behavior and the default editor.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# Load the Powerlevel10k prompt initialization code, which provides a highly customizable prompt with various features.

# Set various Zsh options to customize the behavior of the shell, such as command history behavior and the default editor.

# Oh-My-Zsh Config
# Load the Oh-My-Zsh framework and set various plugins and options for it.

# Set the powerlevel10k theme.
# Set the list of plugins.
# Set the prompt format.
# Disable auto-updates.

# Load oh-my-zsh, with the plugins being sourced before it.

# Custom Config
# Load user-defined configurations to take priority over the default ones.

# Enable all completions.
# Load local config if present, for final overrides.

# Set up Heroku autocomplete.
# Set up FZF for Autojump to work.
# Set up Autojump.
# Set up Brewfile management.
# Set up nvm.
# Set up zsh-syntax-highlighting.
# Load the PATH for the Google Cloud SDK.
# Set up Pyenv and virtualenv-init.
# Set up Foundry.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

######################
## basic zsh config ##

# Set vim keybinds first, so that all plugins know about it.
bindkey -v

# EDITOR is vim.
export EDITOR=vim

# Save each command's timestamp and duration.
setopt EXTENDED_HISTORY

# Expand '=command' as path of command
# e.g.) '=ls' -> '/bin/ls'
setopt EQUALS

# Incrementally append history instead of waiting for exit to write out.
setopt INC_APPEND_HISTORY

# Ignore duplicate commands.
setopt HIST_IGNORE_ALL_DUPS

# Ignore commands that start with a space.
setopt HIST_IGNORE_SPACE

# Reduce blanks in history.
setopt HIST_REDUCE_BLANKS

# Allow for history expansion.
setopt HIST_VERIFY

# Don't clobber files accidentally.
setopt NOCLOBBER

# Evaluate prompt each time it is shown. Allows embedding commands.
setopt PROMPT_SUBST

# Show command execution time stamp in history.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# long date format in ls(1)
# https://www.gnu.org/software/coreutils/manual/html_node/Formatting-file-timestamps.html
export TIME_STYLE=long-iso

######################
## oh-my-zsh config ##
export ZSH=$HOME/.dotfiles/oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

plugins=(
  adb
  common-aliases
  docker
  extract
  fasd
  git
  git-extras
  history
  kubectl
  osx
  shrink-path
  taskwarrior
  vscode
  yarn-autocompletions
  zsh-autosuggestions
  zsh-completions
  direnv
)

PS1='%n@%m $(shrink_path -f)>'

DISABLE_AUTO_UPDATE=true

# oh-my-zsh/lib/key-bindings.zsh sets emacs mode, so we source and reset to vim
source $ZSH/oh-my-zsh.sh # note that this comes AFTER plugins sourced.
bindkey -v

##################################################
# Load custom config last, so it takes priority ##

find ~/.dotfiles/zsh/config ~/.dotfiles/zsh/aliases -type f -name '*.zsh' -print0 | sort -z |
  while IFS= read -r -d $'\0' line; do
    source "$line"
  done

# Load local config if present, for final overrides.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# heroku autocomplete setup
# HEROKU_AC_ZSH_SETUP_PATH=/Users/liam/Library/Caches/heroku/autocomplete/zsh_setup &&
#  test -f $HEROKU_AC_ZSH_SETUP_PATH &&
#  source $HEROKU_AC_ZSH_SETUP_PATH

eval "$(/opt/homebrew/bin/brew shellenv)"

compdef __start_kurtosis kt

export PATH="$PATH:/Users/liam/.foundry/bin"

# fzf setup for autojump to work
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autojump
[[ -s $(brew --prefix)/share/autojump/autojump.zsh ]] && . $(brew --prefix)/share/autojump/autojump.zsh

# As per instructions, load this last so that it wraps ZLE widgets.
source ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# tabtab source for packages
# uninstall by removing these lines
#[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
#[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

. "$HOME/.cargo/env"
export DAGSTER_HOME=/Users/liam/Projects/scraping/dbt/dagster_home

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/liam/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/liam/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/liam/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/liam/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

fpath=(~/.dotfiles/zsh/completions/ $fpath)

autoload -Uz compinit && compinit

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/liam/.lmstudio/bin"
